# Generated by Django 5.2.3 on 2025-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(choices=[('czech', 'Czech'), ('italian', 'Italian'), ('french', 'French'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('japanese', 'Japanese')], max_length=20)),
                ('category', models.CharField(choices=[('all', 'All'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('diet', 'Diet'), ('glutenfree', 'Gluten Free')], default='all', max_length=20)),
                ('calories', models.PositiveIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('nutrients', models.TextField(help_text='Výživové hodnoty (HTML nebo text)')),
                ('ingredients', models.TextField(help_text='Ingredience (HTML nebo text)')),
                ('instructions', models.TextField(help_text='Postup vaření')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
    ]
